apiVersion: v1
kind: Template
labels:
  app: leantime
  name: leantimelabel
  template: leantime-mysql-persistent
message: >-
  The following service(s) have been created in your project: ${NAME},  ${DATABASE_SERVICE_NAME}.

  For more information about using this template, including OpenShift  considerations, see
  https://github.com/gmkumar2005/docker-leantime/blob/master/README.md
metadata:
  annotations:
    description: >-
      Leantime is an open source project management system for small teams and startups written in PHP, Javascript using MySQL. For more information
      about using this template, including OpenShift considerations, see  https://github.com/gmkumar2005/docker-leantime/blob/master/README.md
    icon: play
    iconClass: icon-play
    openshift.io/display-name: Leantime + MySQL
    openshift.io/documentation-url: 'https://github.com/Leantime/leantime'
    openshift.io/long-description: >-
      This template defines resources needed to develop a Leantime application, including a build configuration, application deployment configuration, and
      database deployment configuration.
    openshift.io/provider-display-name: Parkar Consulting Group LLC.
    openshift.io/support-url: 'https://github.com/Leantime/docker-leantime/issues'
    tags: 'quickstart,php,leantime, timesheet, calender, kanban'
    template.openshift.io/bindable: 'false'
  name: leantime
  namespace: leantimestage
  resourceVersion: '9855765'
objects:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: leantime-installer
      labels : 
        name: leantimelabel
    spec:
      activeDeadlineSeconds: 900
      completions: 1
      parallelism: 1
      template:
        spec:
          containers:
            - command:
                - /bin/bash
                - '-x'
                - '-c'
                - |  
                  oc version 
                  # base images 
                  oc import-image phpbase:7.3-fpm-alpine --from=php:7.3-fpm-alpine --confirm -n ${NAMESPACE} 
                  sleep 5
                  oc new-build --name=leantime-basebuild ${NAMESPACE}/phpbase:7.3-fpm-alpine~https://github.com/gmkumar2005/docker-leantime.git   --context-dir=baseimage --strategy=docker --allow-missing-images -n ${NAMESPACE}  
                  sleep 5
                  oc start-build leantime-basebuild --follow -n ${NAMESPACE}  
                  sleep 20
                  oc new-build --name=leantime-build  ${NAMESPACE}/leantime-basebuild~https://github.com/gmkumar2005/docker-leantime.git   --context-dir=leantimeimage --strategy=docker -n ${NAMESPACE} 
                  sleep 60
                  oc start-build leantime-build --follow -n ${NAMESPACE}  
                  # App 
                  oc new-app --name=leantime ${NAMESPACE}/leantime-build:latest   -n ${NAMESPACE} 
                  sleep 20
                  oc create secret generic leantimesecret   --from-literal="database_password=${DATABASE_PASSWORD}" --from-literal="database_user=${DATABASE_USER}" --from-literal="leantime_secret_token=${LEANTIME_SECRET_TOKEN}" --from-literal="lleantime_security_salt=sql${LEANTIME_SECURITY_SALT}" -n ${NAMESPACE}
                  oc set env dc/leantime --from=secret/leantimesecret  -n ${NAMESPACE} 
                  oc set env dc/leantime DATABASE_HOST=${DATABASE_SERVICE_NAME} -n ${NAMESPACE}
                  oc set env dc/leantime DATABASE_NAME=${DATABASE_NAME} -n ${NAMESPACE}
                  oc set triggers dc -l leantime --containers=leantime-app --from-image=leantime-build:latest --manual -n ${NAMESPACE}
                  oc rollout latest dc/leantime -n ${NAMESPACE} 
                  
                  # sleep 5
                  oc expose svc/leantime -n ${NAMESPACE}
                  # mysql start
                  oc new-app --name=${DATABASE_SERVICE_NAME} -e MYSQL_USER=${DATABASE_USER}   -e MYSQL_PASSWORD=${DATABASE_PASSWORD} -e MYSQL_DATABASE=${DATABASE_NAME}   docker.io/centos/mysql-57-centos7:latest -n ${NAMESPACE}

                  oc set resources dc/${DATABASE_SERVICE_NAME} --limits=memory=${MEMORY_MYSQL_LIMIT} 

              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: 'quay.io/openshift/origin-cli:latest'
              name: leantime-installer-job
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          restartPolicy: Never
parameters:
  - description: The name assigned to all of the frontend objects defined in this template.
    displayName: Name
    name: NAME
    required: true
    value: leantime
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: NAMESPACE
    required: true
    value: leantimestage
  - description: Version of PHP image to be used (7.2-fpm-alpine or latest).
    displayName: PHP Version
    name: PHP_VERSION
    required: true
    value: 7.2-fpm-alpine
  - description: Maximum amount of memory the LEANTIME container can use.
    displayName: Memory Limit
    name: MEMORY_LIMIT
    required: true
    value: 512Mi
  - description: Maximum amount of memory the MySQL container can use.
    displayName: Memory Limit (MySQL)
    name: MEMORY_MYSQL_LIMIT
    required: true
    value: 512Mi
  - description: 'Volume space available for data, e.g. 512Mi, 2Gi'
    displayName: Volume Capacity
    name: VOLUME_CAPACITY
    required: true
    value: 1Gi
  - description: The URL of the repository with your application source code.
    displayName: Git Repository URL
    name: SOURCE_REPOSITORY_URL
    required: true
    value: 'https://github.com/gmkumar2005/docker-leantime.git'
  - description: >-
      Set this to a branch name, tag or other ref of your repository if you are
      not using the default branch.
    displayName: Git Reference
    name: SOURCE_REPOSITORY_REF
  - description: >-
      Set this to the relative path to your project if it is not in the root of
      your repository.
    displayName: Context Directory
    name: CONTEXT_DIR
  - description: >-
      The exposed hostname that will route to the LEANTIME service, if left
      blank a value will be defaulted.
    displayName: Application Hostname
    name: APPLICATION_DOMAIN
  - description: >-
      Github trigger secret.  A difficult to guess string encoded as part of the
      webhook URL.  Not encrypted.
    displayName: GitHub Webhook Secret
    from: '[a-zA-Z0-9]{40}'
    generate: expression
    name: GITHUB_WEBHOOK_SECRET
  - description: Database Service Name
    displayName: Database Service Name
    name: DATABASE_SERVICE_NAME
    required: true
    value: leantimemysql
  - description: 'Database engine:  leantimemysql (default).'
    displayName: Database Engine
    name: DATABASE_ENGINE
    required: true
    value: mysql
  - displayName: Database Name
    name: DATABASE_NAME
    required: true
    value: leantime
  - displayName: Database User
    name: DATABASE_USER
    required: true
    value: leantime
  - displayName: Database Password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: DATABASE_PASSWORD
  - description: Set this to a long random string.
    displayName: Leantimme secret token
    from: '[\w]{50}'
    generate: expression
    name: LEANTIME_SECRET_TOKEN
  - description: Security salt for session hash.
    displayName: Leantime Security Salt
    from: '[a-zA-Z0-9]{40}'
    generate: expression
    name: LEANTIME_SECURITY_SALT
  - description: >-
      How often to check script timestamps for updates, in seconds. 0 will
      result in OPcache checking for updates on every request.
    displayName: OPcache Revalidation Frequency
    name: OPCACHE_REVALIDATE_FREQ
    value: '2'
  - description: The custom Composer mirror URL
    displayName: Custom Composer Mirror URL
    name: COMPOSER_MIRROR
